### ISSUE TITLE
strtok() has a static variable

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CMS-370-GCCLIB#42]
strtok() has a static variable (old) which breaks the need for a readonly TEXT segment.

string.c line 517.

**Comment by Rhialto** [comment]
This is generally known to be a problem for use in multithreaded code. So for that they invented the `strtok_r` function, which forces the caller to provide some space.
[Here](https://www.freebsd.org/cgi/man.cgi?query=strtok_r&apropos=0&sektion=0&manpath=NetBSD+9.0&arch=default&format=html) is a manual page.
[Here](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libc/string/strtok_r.c?rev=1.10&content-type=text/x-cvsweb-markup) is an implementation.

There are some more functions that have gotten the same solution with a `foo_r` function.

**Comment by adesutherland** [comment]
> This is generally known to be a problem for use in multithreaded code. So for that they invented the `strtok_r` function, which forces the caller to provide some space.
> [Here](https://www.freebsd.org/cgi/man.cgi?query=strtok_r&apropos=0&sektion=0&manpath=NetBSD+9.0&arch=default&format=html) is a manual page.
> [Here](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libc/string/strtok_r.c?rev=1.10&content-type=text/x-cvsweb-markup) is an implementation.
> 
> There are some more functions that have gotten the same solution with a `foo_r` function.

You are right - this old C90 has some dangerous functions!

**Comment by adesutherland** [comment]
Fixed in f0025
