### ISSUE TITLE
Incorrect parsing of CMS EPLIST command name field

### ISSUE THREAD

**Issue by BobBolch** [adesutherland/CMS-370-GCCLIB#51]
I found this during BREXX testing of the CMS installer code. The parsing of
the EPLIST command name field is incorrect. When a command has no operands (like DMSREX),
and is issued within a CMS EXEC program (like SYSPROF EXEC)  that is a vartiable length file, the
end of the command name is not found correctly. It was not found in the github test environment
because the SYSPROF EXEC had RECFM F.  In CMSRUNTM C from release 0.8.2, change these lines 
starting at line 122:

        a = 0;                                                                
        for (i = 0; i < 8; i++) {                                             
            ch = gcccrab->eplist->Command[i];                                 
            if (ch && ch != 0xFF && ch != ' ') gcccrab->argbuffer[a++] = ch;  
            else break;                                                       
        }     
        gcccrab->argbuffer[a++] = 0;                            
        gcccrab->argv[gcccrab->argc++] = gcccrab->argbuffer;    

Change code to this:

        len = gcccrab->eplist->BeginArgs - gcccrab->eplist->Command;      
        if (len > 8) len = 8;                                             
        a = 0;                                                            
        for (i = 0; i < len; i++) {                                       
            gcccrab->argbuffer[a++] = gcccrab->eplist->Command[i];        
        }

**Comment by adesutherland** [comment]
Fixed in F0049

**Comment by BobBolch** [comment]
Fixed. Thank you.
